### ISSUE TITLE
incorrect version number in bower.json

### ISSUE THREAD

**Issue by jay8t6** [miztroh/wysiwyg-e#220]
bower.json has incorrect version number causing bower install to fail. It has 2.1 while your latest tag is only 2.1.1. Can you fix please?

UPDATE: I get this error below while doing bower install

```
Stack trace:
TypeError: Invalid Version: 2.1
    at new SemVer (/usr/local/lib/node_modules/bower/lib/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/bower/lib/node_modules/semver/semver.js:460:10)
    at Object.neq (/usr/local/lib/node_modules/bower/lib/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:209:56)
    at GitHubResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:134:53)
    at _fulfilled (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 6.14.0
OS: Darwin 17.4.0 x64
```

**Comment by miztroh** [comment]
Good catch.  Resolved in https://github.com/miztroh/wysiwyg-e/releases/tag/v2.1.2.

**Comment by jay8t6** [comment]
@miztroh thanks for getting to this quickly! I appreciate it!
